name: Build a Docker image
on:  
  push:
jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout the repostiory        
        uses: actions/checkout@v4      
      - name: Build the image        
        uses: docker build -t node-app:latest .      
      - name: List the built Docker image        
        run: docker image ls
